### ISSUE TITLE
2.4 CRUD routes for server.js

### ISSUE THREAD

**Issue by drcox23** [maymc/consume-more-stuff#1]
Need establish basic crud routes for server.js

To include:

GET all posts
GET all comments
GET my comments
GET post by id
GET comments by post_id
POST post
POST comment
POST drafted post
PUT drafted post (?)
PUT accepted comments (?)
(additional ones TBD or will create a new issue)

**Comment by chazkondo** [comment]
@drcox23,

Just to clarify, was this meant to be posted to the projects board?

If so, I can update the projects board to represent this enhancement and track it from there- mainly to avoid ubiquity. 

Chaz

**Comment by chazkondo** [comment]
> Need establish basic crud routes for server.js
> 
> To include:
> 
> - [x] GET all posts
> - [x] GET all comments
> - [x] GET my comments
> - [x] GET post by id
> - [x] GET comments by post_id
> - [x] POST post
> - [x] POST comment
> - [x] POST drafted post
> - [x] PUT drafted post (?)
> - [x] PUT accepted comments (?)
> (additional ones TBD or will create a new issue)

- [x] GET drafted posts

Update: We will be working with issue cards moving to the projects board, and track using milestones and labels. Thanks @drcox23

**Comment by chazkondo** [comment]
Thanks @drcox23 - this issue is now closed

**Comment by chazkondo** [comment]
- [x] Initial post save
- [x] Initial comment save
