### ISSUE TITLE
2.6 Readme has no getting started directions

### ISSUE THREAD

**Issue by ba5eem** [maymc/consume-more-stuff#19]
Add quick getting started to the readme, like what i need to do - to get going. You can add  a script in package.json as well - like a setup app script, for example:
```
"setup": "npm i && docker-compose up --build -d && npm run migrate && npm run seed"
```

**Comment by chazkondo** [comment]
@ba5eem 

Thanks for feedback, I have added the following action items for our MVP milestones 
- [x] Create getting started read me
- [x] Create setup script
