### ISSUE TITLE
1.5 Creating a higher-fidelity mockup

### ISSUE THREAD

**Issue by drcox23** [maymc/consume-more-stuff#2]
Just a question, should we consider a higher-fidelity mockup for the site, so we are aligned on the look/feel of the site? 

just a thought

**Comment by chazkondo** [comment]
Hey Doug,

I think this is a good idea. Did you have any platforms in mind? Otherwise we can draw up some pictures/processes (i.e. crud cycle).

Chaz

**Comment by drcox23** [comment]
I was thinking either  figma or invision. They are both free. I think figma is a little easier to get ramped up quicker. I'm not too familiar with either, just have dabbled here and there, so i'm up for whatever. Also, I think we only need a hi-fi mockup for 1 page, maybe just the home page? 

www.figma.com
https://www.invisionapp.com/

**Comment by chazkondo** [comment]
Closing this question as I opened a task item [here](https://github.com/maymc/consume-more-stuff/issues/11)

Thanks for the suggestion, @drcox23
